export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  companySize: string;
  industry: string;
  primaryIndustry: string;
  location: string;
  email: string;
  emailRevealed: boolean;
  phone: string;
  phoneRevealed: boolean;
  department: string;
  managementLevel: string;
  companyRevenue: string;
  linkedinUrl: string;
  avatar: string;
  companyLogo: string;
  accuracy: "A+" | "A" | "B+";
}

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "1",
    firstName: "Robert A.",
    lastName: "Faith",
    title: "Chief Executive Officer & Founder",
    company: "Greystar",
    companySize: "10,001+",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Charleston, SC",
    email: "r.faith@greystar.com",
    emailRevealed: true,
    phone: "(843) 579-9400",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10B+",
    linkedinUrl: "#",
    avatar: "RF",
    companyLogo: "GR",
    accuracy: "A+",
  },
  {
    id: "2",
    firstName: "Rich N.",
    lastName: "Barton",
    title: "Chief Executive Officer & Co-Founder",
    company: "Zillow Group",
    companySize: "5,001–10,000",
    industry: "Real Estate",
    primaryIndustry: "Data Collection & Internet Portals, Me...",
    location: "Seattle, WA",
    email: "r.barton@zillow.com",
    emailRevealed: false,
    phone: "(206) 470-7000",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1B–$5B",
    linkedinUrl: "#",
    avatar: "RB",
    companyLogo: "ZL",
    accuracy: "A+",
  },
  {
    id: "3",
    firstName: "Jim",
    lastName: "Hand",
    title: "Chief Executive Officer & Team Leader",
    company: "Keller Williams Realty",
    companySize: "10,001+",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Austin, TX",
    email: "j.hand@kw.com",
    emailRevealed: true,
    phone: "(512) 327-3070",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10B+",
    linkedinUrl: "#",
    avatar: "JH",
    companyLogo: "KW",
    accuracy: "A",
  },
  {
    id: "4",
    firstName: "Michelle M.",
    lastName: "MacKay",
    title: "Chief Executive Officer",
    company: "Cushman & Wakefield",
    companySize: "10,001+",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Chicago, IL",
    email: "m.mackay@cushmanwakefield.com",
    emailRevealed: false,
    phone: "(312) 470-2000",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$5B–$10B",
    linkedinUrl: "#",
    avatar: "MM",
    companyLogo: "CW",
    accuracy: "A+",
  },
  {
    id: "5",
    firstName: "Ara K.",
    lastName: "Hovnanian",
    title: "Chairman, President & Chief Executive Officer",
    company: "K. Hovnanian",
    companySize: "1,001–5,000",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Matawan, NJ",
    email: "a.hovnanian@khov.com",
    emailRevealed: true,
    phone: "(732) 747-7800",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1B–$5B",
    linkedinUrl: "#",
    avatar: "AH",
    companyLogo: "KH",
    accuracy: "A",
  },
  {
    id: "6",
    firstName: "David",
    lastName: "Simon",
    title: "Chairman, Chief Executive Officer & President",
    company: "Simon Property Group LP",
    companySize: "5,001–10,000",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Indianapolis, IN",
    email: "d.simon@simon.com",
    emailRevealed: false,
    phone: "(317) 636-1600",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$5B–$10B",
    linkedinUrl: "#",
    avatar: "DS",
    companyLogo: "SP",
    accuracy: "A+",
  },
  {
    id: "7",
    firstName: "Michael Patrick",
    lastName: "McCracken",
    title: "Chief Executive Officer & Team Leader",
    company: "Keller Williams Realty",
    companySize: "10,001+",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Austin, TX",
    email: "m.mccracken@kw.com",
    emailRevealed: true,
    phone: "(512) 327-3071",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10B+",
    linkedinUrl: "#",
    avatar: "MM",
    companyLogo: "KW",
    accuracy: "A",
  },
  {
    id: "8",
    firstName: "W. Erik",
    lastName: "Carlson",
    title: "Chief Executive Officer",
    company: "RE/MAX Holdings",
    companySize: "1,001–5,000",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Denver, CO",
    email: "e.carlson@remax.com",
    emailRevealed: false,
    phone: "(303) 770-5531",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$500M–$1B",
    linkedinUrl: "#",
    avatar: "EC",
    companyLogo: "RM",
    accuracy: "A",
  },
  {
    id: "9",
    firstName: "Andrew C",
    lastName: "Florance",
    title: "Founder & Chief Executive Officer",
    company: "CoStar Group",
    companySize: "5,001–10,000",
    industry: "Real Estate",
    primaryIndustry: "Publishing, Media & Internet",
    location: "Washington, DC",
    email: "a.florance@costar.com",
    emailRevealed: true,
    phone: "(202) 346-6500",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1B–$5B",
    linkedinUrl: "#",
    avatar: "AF",
    companyLogo: "CS",
    accuracy: "A+",
  },
  {
    id: "10",
    firstName: "Mark",
    lastName: "Parrell",
    title: "President & Chief Executive Officer",
    company: "Equity Residential",
    companySize: "1,001–5,000",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Chicago, IL",
    email: "m.parrell@equityapartments.com",
    emailRevealed: false,
    phone: "(312) 474-1300",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1B–$5B",
    linkedinUrl: "#",
    avatar: "MP",
    companyLogo: "ER",
    accuracy: "A",
  },
  {
    id: "11",
    firstName: "Owen D.",
    lastName: "Thomas",
    title: "Chief Executive Officer",
    company: "Boston Properties",
    companySize: "1,001–5,000",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Boston, MA",
    email: "o.thomas@bostonproperties.com",
    emailRevealed: true,
    phone: "(617) 236-3300",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1B–$5B",
    linkedinUrl: "#",
    avatar: "OT",
    companyLogo: "BP",
    accuracy: "A+",
  },
  {
    id: "12",
    firstName: "Ryan",
    lastName: "Schneider",
    title: "Chief Executive Officer & President",
    company: "Anywhere Real Estate",
    companySize: "5,001–10,000",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Madison, NJ",
    email: "r.schneider@anywhere.re",
    emailRevealed: false,
    phone: "(973) 407-2000",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$5B–$10B",
    linkedinUrl: "#",
    avatar: "RS",
    companyLogo: "AR",
    accuracy: "A",
  },
];

export const FILTER_OPTIONS = {
  managementLevel: ["C-Suite", "SVP", "VP", "Director", "Manager", "Senior IC", "IC"],
  department: ["Engineering", "Marketing", "Sales", "Product", "Customer Success", "Executive", "Finance", "HR", "Operations"],
  industry: ["Real Estate", "Software", "Financial Services", "Healthcare", "Manufacturing", "Retail", "Media", "Education", "Consulting"],
  companySize: ["1–50", "51–200", "201–500", "501–1,000", "1,001–5,000", "5,001–10,000", "10,001+"],
  companyRevenue: ["<$1M", "$1M–$10M", "$10M–$50M", "$50M–$100M", "$100M–$500M", "$500M–$1B", "$1B–$5B", "$10B+"],
  location: ["Charleston, SC", "Seattle, WA", "Austin, TX", "Chicago, IL", "Denver, CO", "Washington, DC", "Boston, MA", "Indianapolis, IN"],
};
