export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  companySize: string;
  industry: string;
  primaryIndustry: string;
  location: string;
  email: string;
  emailRevealed: boolean;
  phone: string;
  phoneRevealed: boolean;
  department: string;
  managementLevel: string;
  companyRevenue: string;
  linkedinUrl: string;
  avatar: string;
  companyLogo: string;
  accuracy: "A+" | "A" | "B+";
}

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "1",
    firstName: "Ed",
    lastName: "Patton",
    title: "Property Owner & Real Estate Investor",
    company: "Patton Real Estate Holdings",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "e.patton@pattonreholdings.com",
    emailRevealed: true,
    phone: "(210) 555-0101",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "EP",
    companyLogo: "PR",
    accuracy: "A+",
  },
  {
    id: "2",
    firstName: "Dennis R.",
    lastName: "Burroughs",
    title: "Principal & Real Estate Developer",
    company: "Burroughs Development Group",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "d.burroughs@burroughsdev.com",
    emailRevealed: false,
    phone: "(210) 555-0102",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "DB",
    companyLogo: "BD",
    accuracy: "A",
  },
  {
    id: "3",
    firstName: "Justin",
    lastName: "Fowlks",
    title: "Real Estate Agent & Broker",
    company: "Fowlks Realty Group",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "j.fowlks@fowlksrealty.com",
    emailRevealed: true,
    phone: "(210) 555-0103",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Manager",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "JF",
    companyLogo: "FR",
    accuracy: "A+",
  },
  {
    id: "4",
    firstName: "Regina",
    lastName: "Pestorich",
    title: "Licensed Real Estate Agent",
    company: "Highlands Realty Partners",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "r.pestorich@highlandsrealty.com",
    emailRevealed: false,
    phone: "(210) 555-0104",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "RP",
    companyLogo: "HP",
    accuracy: "A",
  },
  {
    id: "5",
    firstName: "Kyle",
    lastName: "Kuster",
    title: "Real Estate Investor",
    company: "Kuster Properties LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "k.kuster@kusterproperties.com",
    emailRevealed: true,
    phone: "(210) 555-0105",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "KK",
    companyLogo: "KP",
    accuracy: "A",
  },
  {
    id: "6",
    firstName: "Daniel",
    lastName: "Gauna",
    title: "Property Manager & Investor",
    company: "Gauna Property Management",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "d.gauna@gaunapm.com",
    emailRevealed: false,
    phone: "(210) 555-0106",
    phoneRevealed: false,
    department: "Operations",
    managementLevel: "Manager",
    companyRevenue: "<$1M",
    linkedinUrl: "#",
    avatar: "DG",
    companyLogo: "GP",
    accuracy: "B+",
  },
  {
    id: "7",
    firstName: "Matthew Lee",
    lastName: "Collier",
    title: "Real Estate Attorney",
    company: "Collier & Associates Law",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "m.collier@collierlaw.com",
    emailRevealed: true,
    phone: "(210) 555-0107",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "MC",
    companyLogo: "CL",
    accuracy: "A+",
  },
  {
    id: "8",
    firstName: "Eduardo",
    lastName: "Gonzales",
    title: "Real Estate Broker",
    company: "Gonzales Real Estate Group",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "e.gonzales@gonzalesreg.com",
    emailRevealed: false,
    phone: "(210) 555-0108",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Manager",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "EG",
    companyLogo: "GR",
    accuracy: "A",
  },
  {
    id: "9",
    firstName: "Robert Christopher",
    lastName: "Benson",
    title: "Director of Acquisitions",
    company: "Benson Capital Real Estate",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "r.benson@bensoncapre.com",
    emailRevealed: true,
    phone: "(210) 555-0109",
    phoneRevealed: false,
    department: "Finance",
    managementLevel: "Director",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "RB",
    companyLogo: "BC",
    accuracy: "A+",
  },
  {
    id: "10",
    firstName: "Abigail",
    lastName: "Alvarez Murillo",
    title: "Residential Real Estate Agent",
    company: "SA Premier Properties",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "a.alvarezm@sapremierprop.com",
    emailRevealed: false,
    phone: "(210) 555-0110",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "AA",
    companyLogo: "SP",
    accuracy: "A",
  },
  {
    id: "11",
    firstName: "Aurora",
    lastName: "Cruz",
    title: "Real Estate Investor & Owner",
    company: "Cruz Family Properties",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "a.cruz@cruzfamilyprop.com",
    emailRevealed: true,
    phone: "(210) 555-0111",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "<$1M",
    linkedinUrl: "#",
    avatar: "AC",
    companyLogo: "CF",
    accuracy: "A",
  },
  {
    id: "12",
    firstName: "Roxana",
    lastName: "Menes",
    title: "Commercial Real Estate Consultant",
    company: "Menes Commercial Realty",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "r.menes@menescre.com",
    emailRevealed: false,
    phone: "(210) 555-0112",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Senior IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "RM",
    companyLogo: "MC",
    accuracy: "A+",
  },
  {
    id: "13",
    firstName: "Eloy E.",
    lastName: "Cuellar",
    title: "Real Estate Developer",
    company: "Cuellar Development Co.",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "e.cuellar@cuellardev.com",
    emailRevealed: true,
    phone: "(210) 555-0113",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "EC",
    companyLogo: "CD",
    accuracy: "A",
  },
  {
    id: "14",
    firstName: "Barry",
    lastName: "Hagendorf",
    title: "Principal Broker",
    company: "Hagendorf Real Estate Partners",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "b.hagendorf@hagendorfre.com",
    emailRevealed: false,
    phone: "(210) 555-0114",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "BH",
    companyLogo: "HR",
    accuracy: "A+",
  },
  {
    id: "15",
    firstName: "Abigail",
    lastName: "Bass",
    title: "Residential Property Buyer",
    company: "Bass Investments SA",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "a.bass@bassinvestsa.com",
    emailRevealed: true,
    phone: "(210) 555-0115",
    phoneRevealed: false,
    department: "Finance",
    managementLevel: "Manager",
    companyRevenue: "<$1M",
    linkedinUrl: "#",
    avatar: "AB",
    companyLogo: "BI",
    accuracy: "B+",
  },
  {
    id: "16",
    firstName: "Rosa Elia",
    lastName: "Muzquiz",
    title: "Licensed Realtor",
    company: "Muzquiz Realty Group",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "r.muzquiz@muzquizrealty.com",
    emailRevealed: false,
    phone: "(210) 555-0116",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Senior IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "RM",
    companyLogo: "MR",
    accuracy: "A",
  },
  {
    id: "17",
    firstName: "Juan J.",
    lastName: "Bass Jr.",
    title: "Real Estate Investor",
    company: "Bass Property Group",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "j.bass@basspropgroup.com",
    emailRevealed: true,
    phone: "(210) 555-0117",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "JB",
    companyLogo: "BG",
    accuracy: "A+",
  },
  {
    id: "18",
    firstName: "Tom",
    lastName: "Sensing",
    title: "Real Estate Agent",
    company: "Sensing Residential Realty",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "t.sensing@sensingrealty.com",
    emailRevealed: false,
    phone: "(210) 555-0118",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "TS",
    companyLogo: "SR",
    accuracy: "A",
  },
  {
    id: "19",
    firstName: "Arnulfo",
    lastName: "Garcia",
    title: "Property Owner & Landlord",
    company: "Garcia Property Holdings",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "a.garcia@garciaprophold.com",
    emailRevealed: true,
    phone: "(210) 555-0119",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "<$1M",
    linkedinUrl: "#",
    avatar: "AG",
    companyLogo: "GP",
    accuracy: "B+",
  },
  {
    id: "20",
    firstName: "Maria E.",
    lastName: "Reyes",
    title: "Residential Realtor",
    company: "Reyes Home Solutions",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "m.reyes@reyeshomesol.com",
    emailRevealed: false,
    phone: "(210) 555-0120",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "MR",
    companyLogo: "RH",
    accuracy: "A",
  },
  {
    id: "21",
    firstName: "Alexander James",
    lastName: "Folks",
    title: "Real Estate Developer",
    company: "Folks Land Holdings",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "a.folks@folkslh.com",
    emailRevealed: true,
    phone: "(210) 555-0121",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "AF",
    companyLogo: "FL",
    accuracy: "A+",
  },
  {
    id: "22",
    firstName: "Marc Henri J.",
    lastName: "Cerar",
    title: "Commercial Property Investor",
    company: "Cerar Capital Group",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Converse, TX",
    email: "m.cerar@cerarcapital.com",
    emailRevealed: false,
    phone: "(210) 555-0122",
    phoneRevealed: false,
    department: "Finance",
    managementLevel: "Director",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "MC",
    companyLogo: "CC",
    accuracy: "A",
  },
  {
    id: "23",
    firstName: "Edward A.",
    lastName: "Gonzalez",
    title: "Real Estate Broker & Investor",
    company: "Gonzalez Realty Advisors",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "e.gonzalez@gonzalezra.com",
    emailRevealed: true,
    phone: "(210) 555-0123",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Manager",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "EG",
    companyLogo: "GA",
    accuracy: "A+",
  },
  {
    id: "24",
    firstName: "Nelson Blake",
    lastName: "Farris",
    title: "Senior Real Estate Agent",
    company: "Farris & Associates Realty",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "n.farris@farrisrealty.com",
    emailRevealed: false,
    phone: "(210) 555-0124",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Senior IC",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "NF",
    companyLogo: "FA",
    accuracy: "A",
  },
  {
    id: "25",
    firstName: "Michael",
    lastName: "Klocek",
    title: "Property Investor & Manager",
    company: "Klocek Real Estate LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "m.klocek@klocekre.com",
    emailRevealed: true,
    phone: "(210) 555-0125",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "MK",
    companyLogo: "KR",
    accuracy: "A",
  },
  {
    id: "26",
    firstName: "Jack",
    lastName: "Jinglejangle",
    title: "Managing Principal",
    company: "Jinglejangle RE LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Houston, TX",
    email: "j.jinglejangle@jinglejangle.re",
    emailRevealed: true,
    phone: "(713) 555-0126",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "JJ",
    companyLogo: "JR",
    accuracy: "A+",
  },
  {
    id: "27",
    firstName: "Sam",
    lastName: "Santikos",
    title: "Chief Executive Officer",
    company: "Santikos Legacy LLC",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "La Jolla, CA",
    email: "s.santikos@santikoslegacy.com",
    emailRevealed: false,
    phone: "(858) 555-0127",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$50M–$100M",
    linkedinUrl: "#",
    avatar: "SS",
    companyLogo: "SL",
    accuracy: "A+",
  },
  {
    id: "28",
    firstName: "Marcus",
    lastName: "Mosaic",
    title: "Founder & Principal",
    company: "Mosaic Moc SA LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Houston, TX",
    email: "m.mosaic@mosaicmocsa.com",
    emailRevealed: true,
    phone: "(713) 555-0128",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "MM",
    companyLogo: "MS",
    accuracy: "A",
  },
  {
    id: "29",
    firstName: "Frank",
    lastName: "Fortress",
    title: "Managing Director",
    company: "Fortress Group",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "f.fortress@fortressgroup.com",
    emailRevealed: false,
    phone: "(210) 555-0129",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$100M–$500M",
    linkedinUrl: "#",
    avatar: "FF",
    companyLogo: "FG",
    accuracy: "A+",
  },
  {
    id: "30",
    firstName: "Harry",
    lastName: "Hoppenstein",
    title: "President & Principal",
    company: "Hoppenstein Properties Inc.",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "Richardson, TX",
    email: "h.hoppenstein@hoppensteinprop.com",
    emailRevealed: true,
    phone: "(972) 555-0130",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$50M–$100M",
    linkedinUrl: "#",
    avatar: "HH",
    companyLogo: "HP",
    accuracy: "A",
  },
  {
    id: "31",
    firstName: "Brian",
    lastName: "Brogal",
    title: "Investment Manager",
    company: "Brogal Investment LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "b.brogal@brogalinvest.com",
    emailRevealed: false,
    phone: "(210) 555-0131",
    phoneRevealed: false,
    department: "Finance",
    managementLevel: "Director",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "BB",
    companyLogo: "BI",
    accuracy: "A",
  },
  {
    id: "32",
    firstName: "Kevin",
    lastName: "Bexar",
    title: "Managing Partner",
    company: "Bexar KJS Group LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "k.bexar@bexarkjs.com",
    emailRevealed: true,
    phone: "(210) 555-0132",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "KB",
    companyLogo: "BK",
    accuracy: "A+",
  },
  {
    id: "33",
    firstName: "Ryan",
    lastName: "Riocap",
    title: "Chief Investment Officer",
    company: "Riocap The Legacy LLC",
    companySize: "51–200",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "La Jolla, CA",
    email: "r.riocap@riocaplegacy.com",
    emailRevealed: false,
    phone: "(858) 555-0133",
    phoneRevealed: false,
    department: "Finance",
    managementLevel: "C-Suite",
    companyRevenue: "$50M–$100M",
    linkedinUrl: "#",
    avatar: "RR",
    companyLogo: "RL",
    accuracy: "A",
  },
  {
    id: "34",
    firstName: "Sam",
    lastName: "Sawtooth",
    title: "Founder & Developer",
    company: "Sawtooth San Antonio LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "s.sawtooth@sawtoothsa.com",
    emailRevealed: true,
    phone: "(210) 555-0134",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$10M–$50M",
    linkedinUrl: "#",
    avatar: "SS",
    companyLogo: "SA",
    accuracy: "A+",
  },
  {
    id: "35",
    firstName: "Rachel",
    lastName: "Riverreach",
    title: "Director of Residential Acquisitions",
    company: "River Reach Dwelling LLC",
    companySize: "1–50",
    industry: "Real Estate",
    primaryIndustry: "Real Estate",
    location: "San Antonio, TX",
    email: "r.riverreach@riverreachdwelling.com",
    emailRevealed: false,
    phone: "(210) 555-0135",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "Director",
    companyRevenue: "$1M–$10M",
    linkedinUrl: "#",
    avatar: "RR",
    companyLogo: "RD",
    accuracy: "A",
  },
];

export const FILTER_OPTIONS = {
  managementLevel: ["C-Suite", "SVP", "VP", "Director", "Manager", "Senior IC", "IC"],
  department: ["Engineering", "Marketing", "Sales", "Product", "Customer Success", "Executive", "Finance", "HR", "Operations"],
  industry: ["Real Estate", "Software", "Financial Services", "Healthcare", "Manufacturing", "Retail", "Media", "Education", "Consulting"],
  companySize: ["1–50", "51–200", "201–500", "501–1,000", "1,001–5,000", "5,001–10,000", "10,001+"],
  companyRevenue: ["<$1M", "$1M–$10M", "$10M–$50M", "$50M–$100M", "$100M–$500M", "$500M–$1B", "$1B–$5B", "$10B+"],
  location: ["San Antonio, TX", "Converse, TX", "Charleston, SC", "Seattle, WA", "Austin, TX", "Chicago, IL", "Denver, CO", "Washington, DC"],
};
