export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  companySize: string;
  industry: string;
  location: string;
  email: string;
  emailRevealed: boolean;
  phone: string;
  phoneRevealed: boolean;
  department: string;
  managementLevel: string;
  companyRevenue: string;
  linkedinUrl: string;
  avatar: string;
  companyLogo: string;
}

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "1",
    firstName: "Sarah",
    lastName: "Mitchell",
    title: "VP of Marketing",
    company: "Salesforce",
    companySize: "10,001+",
    industry: "Software",
    location: "San Francisco, CA",
    email: "s.mitchell@salesforce.com",
    emailRevealed: true,
    phone: "(415) 555-0142",
    phoneRevealed: false,
    department: "Marketing",
    managementLevel: "VP",
    companyRevenue: "$10B+",
    linkedinUrl: "#",
    avatar: "SM",
    companyLogo: "SF",
  },
  {
    id: "2",
    firstName: "James",
    lastName: "Kowalski",
    title: "Director of Engineering",
    company: "HubSpot",
    companySize: "1,001–5,000",
    industry: "Software",
    location: "Boston, MA",
    email: "j.kowalski@hubspot.com",
    emailRevealed: true,
    phone: "(617) 555-0198",
    phoneRevealed: false,
    department: "Engineering",
    managementLevel: "Director",
    companyRevenue: "$500M–$1B",
    linkedinUrl: "#",
    avatar: "JK",
    companyLogo: "HS",
  },
  {
    id: "3",
    firstName: "Priya",
    lastName: "Nair",
    title: "Chief Revenue Officer",
    company: "Zendesk",
    companySize: "1,001–5,000",
    industry: "Software",
    location: "San Francisco, CA",
    email: "p.nair@zendesk.com",
    emailRevealed: false,
    phone: "(415) 555-0277",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "C-Suite",
    companyRevenue: "$500M–$1B",
    linkedinUrl: "#",
    avatar: "PN",
    companyLogo: "ZD",
  },
  {
    id: "4",
    firstName: "Marcus",
    lastName: "Thompson",
    title: "Head of Product",
    company: "Atlassian",
    companySize: "5,001–10,000",
    industry: "Software",
    location: "Austin, TX",
    email: "m.thompson@atlassian.com",
    emailRevealed: true,
    phone: "(512) 555-0311",
    phoneRevealed: false,
    department: "Product",
    managementLevel: "Director",
    companyRevenue: "$1B–$5B",
    linkedinUrl: "#",
    avatar: "MT",
    companyLogo: "AT",
  },
  {
    id: "5",
    firstName: "Elena",
    lastName: "Vasquez",
    title: "SVP of Sales",
    company: "Twilio",
    companySize: "1,001–5,000",
    industry: "Software",
    location: "Denver, CO",
    email: "e.vasquez@twilio.com",
    emailRevealed: false,
    phone: "(720) 555-0455",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "SVP",
    companyRevenue: "$500M–$1B",
    linkedinUrl: "#",
    avatar: "EV",
    companyLogo: "TW",
  },
  {
    id: "6",
    firstName: "David",
    lastName: "Chen",
    title: "Senior Account Executive",
    company: "Snowflake",
    companySize: "1,001–5,000",
    industry: "Software",
    location: "New York, NY",
    email: "d.chen@snowflake.com",
    emailRevealed: true,
    phone: "(212) 555-0512",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Senior IC",
    companyRevenue: "$500M–$1B",
    linkedinUrl: "#",
    avatar: "DC",
    companyLogo: "SN",
  },
  {
    id: "7",
    firstName: "Rachel",
    lastName: "O'Brien",
    title: "Marketing Operations Manager",
    company: "Drift",
    companySize: "201–500",
    industry: "Software",
    location: "Boston, MA",
    email: "r.obrien@drift.com",
    emailRevealed: true,
    phone: "(617) 555-0623",
    phoneRevealed: false,
    department: "Marketing",
    managementLevel: "Manager",
    companyRevenue: "$50M–$100M",
    linkedinUrl: "#",
    avatar: "RO",
    companyLogo: "DR",
  },
  {
    id: "8",
    firstName: "Carlos",
    lastName: "Mendoza",
    title: "CEO",
    company: "Gong.io",
    companySize: "501–1,000",
    industry: "Software",
    location: "San Francisco, CA",
    email: "c.mendoza@gong.io",
    emailRevealed: false,
    phone: "(415) 555-0788",
    phoneRevealed: false,
    department: "Executive",
    managementLevel: "C-Suite",
    companyRevenue: "$100M–$500M",
    linkedinUrl: "#",
    avatar: "CM",
    companyLogo: "GO",
  },
  {
    id: "9",
    firstName: "Jennifer",
    lastName: "Walsh",
    title: "Director of Customer Success",
    company: "Gainsight",
    companySize: "501–1,000",
    industry: "Software",
    location: "Chicago, IL",
    email: "j.walsh@gainsight.com",
    emailRevealed: true,
    phone: "(312) 555-0844",
    phoneRevealed: false,
    department: "Customer Success",
    managementLevel: "Director",
    companyRevenue: "$100M–$500M",
    linkedinUrl: "#",
    avatar: "JW",
    companyLogo: "GS",
  },
  {
    id: "10",
    firstName: "Alex",
    lastName: "Patel",
    title: "VP of Engineering",
    company: "Datadog",
    companySize: "1,001–5,000",
    industry: "Software",
    location: "New York, NY",
    email: "a.patel@datadog.com",
    emailRevealed: false,
    phone: "(212) 555-0921",
    phoneRevealed: false,
    department: "Engineering",
    managementLevel: "VP",
    companyRevenue: "$500M–$1B",
    linkedinUrl: "#",
    avatar: "AP",
    companyLogo: "DD",
  },
  {
    id: "11",
    firstName: "Natalie",
    lastName: "Brooks",
    title: "Chief Marketing Officer",
    company: "Intercom",
    companySize: "501–1,000",
    industry: "Software",
    location: "San Francisco, CA",
    email: "n.brooks@intercom.com",
    emailRevealed: true,
    phone: "(415) 555-1034",
    phoneRevealed: false,
    department: "Marketing",
    managementLevel: "C-Suite",
    companyRevenue: "$100M–$500M",
    linkedinUrl: "#",
    avatar: "NB",
    companyLogo: "IC",
  },
  {
    id: "12",
    firstName: "Tyler",
    lastName: "Robinson",
    title: "Enterprise Account Manager",
    company: "Outreach",
    companySize: "501–1,000",
    industry: "Software",
    location: "Seattle, WA",
    email: "t.robinson@outreach.io",
    emailRevealed: true,
    phone: "(206) 555-1145",
    phoneRevealed: false,
    department: "Sales",
    managementLevel: "Senior IC",
    companyRevenue: "$100M–$500M",
    linkedinUrl: "#",
    avatar: "TR",
    companyLogo: "OR",
  },
];

export const FILTER_OPTIONS = {
  managementLevel: ["C-Suite", "SVP", "VP", "Director", "Manager", "Senior IC", "IC"],
  department: ["Engineering", "Marketing", "Sales", "Product", "Customer Success", "Executive", "Finance", "HR", "Operations"],
  industry: ["Software", "Financial Services", "Healthcare", "Manufacturing", "Retail", "Media", "Education", "Consulting"],
  companySize: ["1–50", "51–200", "201–500", "501–1,000", "1,001–5,000", "5,001–10,000", "10,001+"],
  companyRevenue: ["<$1M", "$1M–$10M", "$10M–$50M", "$50M–$100M", "$100M–$500M", "$500M–$1B", "$1B–$5B", "$10B+"],
  location: ["San Francisco, CA", "New York, NY", "Boston, MA", "Austin, TX", "Seattle, WA", "Chicago, IL", "Denver, CO", "Los Angeles, CA"],
};
